name: "Roam Research backup"

on:
  push:
    branches:
      - main
  schedule:
      - cron: "50 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ secrets.BACKUP_REPO }}
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      
      - name: Run Backup
        run: |
          cd /tmp
          git clone -q https://github.com/everruler12/roam2github.git roam2github
          cd $_
          npm i
          npm run backup -s
        env:
          ROAM_EMAIL: ${{ secrets.ROAM_EMAIL }}
          ROAM_PASSWORD: ${{ secrets.ROAM_PASSWORD }}
          ROAM_GRAPH: ${{ secrets.ROAM_GRAPH }}
          BACKUP_EDN: true
          BACKUP_JSON: true
          BACKUP_MARKDOWN: true

      - name: Log Timestamp
        run: |
          echo "Backup performed on $(date)" >> backup_log.txt
      
      - name: Commit log
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backup_log.txt
          git commit -m "Update backup log"
          git push
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Commit Changes
        uses: everruler12/git-auto-commit-action@latest
        with:
          commit_message: Automatic backup
